### PR TITLE
[MMC-1807] Clone the internal version of the Mailchimp Android SDK

### PR DESCRIPTION
**Pull request by charlie-mcknight**
This clones the internal SDK repo. Once this is merged the source code will be available to the public. We are also naming this version 0.1.0 and the changelog has been updated accordingly.

*Testing*
1. Clone the repo.
2. Attempt to build the Demo-App
3. Make sure all unit tests pass
4. Make sure all integration tests pass
5. Do a quick glance to make sure that nothing is being committed that shouldn't be (.idea files etc.)

### CODE REVIEW

**Comment by charlie-mcknight** [comment]
As a heads up, I also updated the changelog. We are calling this version 0.1.0.

**Comment by sean-farrell** [comment]
Hypothetical situation but are there any keys we need to make sure the public does not get a hold of? Can we do a command + f to search for it so I manually do not have to look for such a key?

**Comment by charlie-mcknight** [comment]
> Hypothetical situation but are there any keys we need to make sure the public does not get a hold of? Can we do a command + f to search for it so I manually do not have to look for such a key?

Good thought! We should have already removed all keys and I believe the security team has already searched to make sure we don't have any. The only one I could think we might have left in would be an api key. If so I search for `-us` should return any of such keys.

**Comment by paul-turner** [comment]
I looked earlier and couldn't find any either.

**Pull request merged**
